In [2]:
import numpy as np


In [3]:
a=np.array([1,2,3,4,5])
print(a);

[1 2 3 4 5]


In [4]:
a=np.array([1,2,3,4,5])
print(a);
print(a.shape,a.ndim,a.dtype,np.linalg.matrix_rank(a))

[1 2 3 4 5]
(5,) 1 int32 1


In [5]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(b);
print(b.shape,b.ndim,b.dtype,np.linalg.matrix_rank(b))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
(3, 5) 2 int32 2


In [6]:
# Array creation
c=np.array([[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(c);
print(c.shape,c.ndim,c.dtype,np.linalg.matrix_rank(c))

[[16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
(3, 5) 2 int32 2


In [7]:
A=np.arange(3)
print(A)
A=np.arange(1,5)
print(A)
A=A.reshape(2,2)
print(A)
A=np.arange(9)
A.resize(3,3)
print(A)

[0 1 2]
[1 2 3 4]
[[1 2]
 [3 4]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
# Indexing / Slicing
X=a
print(X[0],X[:2],X[1:3])

1 [1 2] [2 3]


In [9]:
X[0]=-99
print(a)
X[0]=1
print(a)

[-99   2   3   4   5]
[1 2 3 4 5]


In [10]:
X=b
print(X[0],X[:2],X[1:3],sep='\n')

[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [11]:
print(X[:,0],X[:2,0:2],X[1,0:2],sep='\n')

[ 1  6 11]
[[1 2]
 [6 7]]
[6 7]


In [12]:
print(X[:,0:1],X[:2,0:2],X[1:2,0:2],sep='\n')

[[ 1]
 [ 6]
 [11]]
[[1 2]
 [6 7]]
[[6 7]]


In [13]:
Y=X[1:3,1:3]
print(Y)

[[ 7  8]
 [12 13]]


In [14]:
Y[0,0]=-99
print(X,b,sep='\n')

[[  1   2   3   4   5]
 [  6 -99   8   9  10]
 [ 11  12  13  14  15]]
[[  1   2   3   4   5]
 [  6 -99   8   9  10]
 [ 11  12  13  14  15]]


In [15]:
# Array arthematic operations and other functions

In [16]:
print(a)
print(a+2,a-2,a*2,a/2,sep='\n')

[1 2 3 4 5]
[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [17]:
np.add(a,2)

array([3, 4, 5, 6, 7])

In [18]:
# Exercise: use operators and other arithmetic functions with arrays a and b

In [19]:
print(a.sum(),b.sum(axis=0),b.sum(axis=-1),b.sum())

15 [ 18 -85  24  27  30] [ 15 -66  65] 14


In [20]:
print(np.sin(a),np.log(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427] [0.         0.69314718 1.09861229 1.38629436 1.60943791]


Exercise: use other functions with arrays a and b# 
In-built array creation

In [21]:
A=np.ones((3,4))
A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
A=np.zeros((3,4))
A

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
A=np.diag([1,2,3])
A

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [24]:
B=np.eye(4)
B

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
B=np.random.random((3,4))
B

array([[0.62456581, 0.42483779, 0.83975796, 0.88308469],
       [0.89048277, 0.69029868, 0.74381475, 0.44566565],
       [0.55531179, 0.87248127, 0.27262609, 0.32948218]])

#Matrix operations 

In [26]:
X=np.array([1,2,3])
Y=np.array([-1,1,2])
print(X.dot(Y))
print(X@Y)

7
7


In [27]:
A=np.array([[1,2],[3,4]])
B=np.array([[1,0,1],[2,2,2]])
C=A.dot(B)
print(A,B,C,sep='\n')
C=A@B
print(C)

[[1 2]
 [3 4]]
[[1 0 1]
 [2 2 2]]
[[ 5  4  5]
 [11  8 11]]
[[ 5  4  5]
 [11  8 11]]


In [28]:
#2x+3y=1
#3x-y = 7
A=np.array([[2,3],[3,-1]])
B=np.array([[1],[7]])
C=np.linalg.inv(A)@B
print(C)

[[ 2.]
 [-1.]]


# Insert a row or col of values

In [29]:
X=np.insert(A,0,1,axis=-1)
#array,index,value, axis
X

array([[ 1,  2,  3],
       [ 1,  3, -1]])

In [30]:
X=np.insert(A,2,1,axis=0)
X

array([[ 2,  3],
       [ 3, -1],
       [ 1,  1]])

# Broadcasting

In [31]:
a=np.arange(3)
print(a)
print(a+5)

[0 1 2]
[5 6 7]


In [32]:
a=np.ones((3,3))
print(a)
b=np.arange(3)
print(b)
print(a+b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [33]:
a=np.arange(3).reshape(3,1)
print('a=',a)
b=np.arange(3)
print('b=',b)
print('a+b=',a+b)

a= [[0]
 [1]
 [2]]
b= [0 1 2]
a+b= [[0 1 2]
 [1 2 3]
 [2 3 4]]
